import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { makeDemoData } from './demo-data.mjs';
import { api, caption, chapter, checkpoint, humanClick, humanType, installOverlays, timingFor } from './demo-helpers.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const out=path.join(root,'test-results','demo-tour');
const mode=(process.argv.find(x=>x.startsWith('--mode='))?.split('=')[1] || process.argv[process.argv.indexOf('--mode')+1] || 'qa').toLowerCase();
if(!['qa','guide'].includes(mode)) throw new Error('Dùng --mode qa hoặc --mode guide');
const base=(process.env.MESFLOW_BASE_URL||'https://mesflow.net').replace(/\/$/,'');
const username=process.env.MESFLOW_USERNAME||'admin', password=process.env.MESFLOW_PASSWORD;
if(!password) throw new Error('Thiếu MESFLOW_PASSWORD (credential không được lưu trong repo).');
const timing=timingFor(mode), data=makeDemoData(), started=new Date();
const chapters=[], consoleErrors=[], networkErrors=[], uiIssues=[]; let current='Khởi động', browser, context, page, videoPath='';
await fs.rm(out,{recursive:true,force:true}); await fs.mkdir(out,{recursive:true}); await fs.mkdir(path.join(out,'screenshots'),{recursive:true});

async function nav(id,label){const l=page.locator(`.nav-item[data-page="${id}"],.sidebar-sub-item[data-page="${id}"]`).first();if(!await l.isVisible().catch(()=>false)){await l.evaluate(el=>{const group=el.closest('.sidebar-group');const trigger=group?.querySelector('.sidebar-group-trigger');if(trigger&&!group.classList.contains('open'))trigger.click()});await page.waitForTimeout(150)}await humanClick(page,l,`Mở ${label}`,timing);await page.locator('#content').waitFor({state:'visible'});await page.waitForTimeout(timing.page)}
async function selectByText(select,needle){await select.waitFor({state:'visible'});let value='';for(let i=0;i<30&&!value;i++){value=await select.locator('option').evaluateAll((xs,n)=>xs.find(x=>(x.textContent||'').includes(n))?.value||'',needle);if(!value)await page.waitForTimeout(500)}if(!value)throw new Error(`Không tìm thấy option chứa: ${needle}`);await select.selectOption(value)}
async function runChapter(number,title,fn){current=title;await chapter(page,number,title,timing.chapter);try{await fn();chapters.push({number,title,result:'PASS'})}catch(e){chapters.push({number,title,result:'FAIL',reason:e.message});throw e}}
async function login(){await page.goto(`${base}/login`,{waitUntil:'domcontentloaded'});const userField=page.locator('input[name="username"],#username').first(),passField=page.locator('input[name="password"],#password').first();if(await userField.isVisible().catch(()=>false)){await userField.fill(username);await passField.fill(password);await page.locator('button[type="submit"]').first().click()}await page.waitForURL(/\/app/,{timeout:20000});await page.waitForSelector('.nav-item[data-page="overview"]',{timeout:20000});await installOverlays(page)}
async function ensureData(){
  const employeeList=await api(page,'/api/employees?limit=1000'); let emp=employeeList.items.find(x=>x.employee_no===data.employeeCode);
  if(!emp) emp=(await api(page,'/api/employees',{method:'POST',body:{employee_no:data.employeeCode,name:data.employeeName,department:'Xưởng demo',team:'Video Guide',position:'Công nhân',employment_status:'Đang làm',active:true}})).item;
  const templates=await api(page,'/api/templates?limit=1000'); let tpl=templates.items.find(x=>x.code===data.templateCode);
  if(!tpl){tpl=(await api(page,'/api/templates',{method:'POST',body:{code:data.templateCode,name:data.templateName,product:'HỘP THÉP',version:'1.0',active:true}})).item;
    await api(page,`/api/templates/${tpl.id}/tree`,{method:'PUT',body:{parts:[{key:'part-1',code:data.partCode,name:data.partName,sort_order:0}],operations:data.operations.map((x,i)=>({part_key:'part-1',code:x.code,name:x.name,sort_order:i,standard_seconds_per_unit:x.seconds,input_flow_enabled:false,defects_consume_input:true})),equipment:[]}})}
  let pos=await api(page,'/api/production-orders?limit=1000');let po=pos.items.find(x=>x.code===data.poCode);
  if(!po){const made=await api(page,`/api/templates/${tpl.id}/instantiate`,{method:'POST',body:{code:data.poCode,planned_quantity:100,priority:'NORMAL',notes:'Dữ liệu riêng cho video hướng dẫn MESFlow'}});po=(await api(page,`/api/production-orders/${made.production_order_id}`)).item}
  if(!['IN_PROGRESS','COMPLETED'].includes(po.status)){await api(page,`/api/production-orders/${po.id}/start`,{method:'POST',body:{}});po=(await api(page,`/api/production-orders/${po.id}`)).item}
  return {employee:emp,template:tpl,po};
}
async function kioskEntry(good,defect,rework,shot){
  await page.goto(`${base}/kiosk`,{waitUntil:'domcontentloaded'});await installOverlays(page);await humanClick(page,page.locator('#demo-toggle'),'Mở bảng quét QR demo',timing);await page.locator('#demo-content').waitFor({state:'visible'});
  await selectByText(page.locator('#demo-employee'),data.employeeCode);await selectByText(page.locator('#demo-operation'),data.operations.at(-1).code);
  await humanClick(page,page.locator('#demo-scan-employee'),'Quét mã nhân viên',timing);await humanClick(page,page.locator('#demo-close'),'Đóng bảng QR',timing);await page.locator('#screen-operation.active').waitFor();await humanClick(page,page.locator('#demo-toggle'),'Chọn QR công đoạn',timing);await humanClick(page,page.locator('#demo-scan-operation'),'Quét mã công đoạn',timing);await humanClick(page,page.locator('#demo-close'),'Đóng bảng QR',timing);
  await page.locator('#screen-started.active').waitFor({timeout:15000});await page.waitForTimeout(3800);await humanClick(page,page.locator('#demo-toggle'),'Mở bảng QR để kết thúc công việc',timing);await humanClick(page,page.locator('#demo-scan-employee'),'Quét lại thẻ nhân viên',timing);await humanClick(page,page.locator('#demo-close'),'Đóng bảng QR',timing);
  await page.locator('#screen-quantity-good.active').waitFor();await humanType(page,page.locator('#good-qty'),good,'Nhập số sản phẩm đạt',timing);await checkpoint(page,path.join(out,'screenshots'),`${shot}-good`);await humanClick(page,page.locator('#good-next'),'Tiếp tục nhập sản phẩm lỗi',timing);
  await humanType(page,page.locator('#defect-qty'),defect,'Nhập tổng số sản phẩm lỗi',timing);await checkpoint(page,path.join(out,'screenshots'),`${shot}-defect`);await humanClick(page,page.locator('#defect-next'),'Tiếp tục',timing);
  if(defect>0){await page.locator('#screen-ask-rework.active').waitFor();if(rework>0){await humanClick(page,page.locator('#rework-yes'),`Trong ${defect} sản phẩm lỗi có ${rework} sản phẩm sửa được`,timing);await humanType(page,page.locator('#rework-qty'),rework,'Nhập số lỗi sửa được',timing);await checkpoint(page,path.join(out,'screenshots'),`${shot}-repairable`);await humanClick(page,page.locator('#rework-next'),'Xem bản xác nhận',timing)}else await humanClick(page,page.locator('#rework-none'),'Không có lỗi sửa được',timing)}
  await page.locator('#screen-finish-confirm.active').waitFor();if(await page.locator('#finish-submit-retry').isVisible().catch(()=>false)){const issue='Nút “# THỬ LẠI” đang hiện trên màn XÁC NHẬN dù có thuộc tính hidden; CSS đang ghi đè semantics [hidden].';if(!uiIssues.includes(issue))uiIssues.push(issue)}await caption(page,`${defect-rework} sản phẩm còn lại được tính là phế`,true);await checkpoint(page,path.join(out,'screenshots'),`${shot}-confirm`);await page.waitForTimeout(timing.important);await caption(page,'',false);await humanClick(page,page.locator('#finish-confirm-ok'),'Xác nhận sản lượng',timing);await page.locator('#screen-finished.active').waitFor({timeout:15000});await page.waitForTimeout(timing.important);
}

try{
  browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:path.join(out,'raw'),size:{width:1920,height:1080}}});page=await context.newPage();
  page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('requestfailed',r=>networkErrors.push(`${r.method()} ${r.url()} · ${r.failure()?.errorText}`));await login();const version=(await page.locator('.version,.app-version').first().textContent().catch(()=>''))||'65.8.44.21';
  await runChapter(1,'TỔNG QUAN SẢN XUẤT',async()=>{await nav('overview','Tổng quan sản xuất');await checkpoint(page,path.join(out,'screenshots'),'01-dashboard');await page.waitForTimeout(timing.important)});
  await runChapter(2,'QUẢN LÝ NHÂN VIÊN',async()=>{await nav('employees','Quản lý nhân viên');await humanClick(page,page.locator('#employeeAdd'), 'Tạo nhân viên dành riêng cho video',timing);await humanType(page,page.locator('#employeeForm [name="employee_no"]'),data.employeeCode,'Nhập mã nhân viên demo',timing);await humanType(page,page.locator('#employeeForm [name="name"]'),data.employeeName,'Nhập họ tên nhân viên',timing);await humanClick(page,page.locator('#employeeForm button[type="submit"]'),'Lưu nhân viên',timing);await page.locator('#employeeSearch').fill(data.employeeCode);await page.waitForTimeout(timing.page);await checkpoint(page,path.join(out,'screenshots'),'02-employees')});
  const entities=await ensureData();
  await runChapter(3,'TEMPLATE QUY TRÌNH',async()=>{await nav('templates','Template');await page.locator('#tplSearch').fill(data.templateCode).catch(()=>{});await page.waitForTimeout(timing.page);await checkpoint(page,path.join(out,'screenshots'),'03-template')});
  await runChapter(4,'TẠO VÀ KHỞI ĐỘNG PO',async()=>{await nav('production-orders','Production Order');const search=page.locator('#poSearch,input[placeholder*="Tìm"]').first();if(await search.count())await search.fill(data.poCode);await page.waitForTimeout(timing.page);await checkpoint(page,path.join(out,'screenshots'),'04-po-created');await checkpoint(page,path.join(out,'screenshots'),'05-po-started')});
  await runChapter(5,'GHI NHẬN SẢN XUẤT TẠI KIOSK',async()=>{await kioskEntry(22,3,1,'06');await kioskEntry(15,0,0,'07');await kioskEntry(18,2,0,'08')});
  await runChapter(6,'TỔNG QUAN SAU SẢN XUẤT',async()=>{await page.goto(`${base}/app`,{waitUntil:'domcontentloaded'});await installOverlays(page);await nav('overview','Tổng quan sản xuất');const filter=page.locator('#overviewPoFilter');if(await filter.count())await selectByText(filter,data.poCode);await checkpoint(page,path.join(out,'screenshots'),'10-dashboard-after-production');await page.waitForTimeout(timing.important)});
  await runChapter(7,'TIẾN TRÌNH SẢN XUẤT',async()=>{await nav('production-schedule','Gantt & Material Flow');const f=page.locator('#schedulePoFilter');await selectByText(f,data.poCode);await page.waitForTimeout(timing.page);await page.mouse.wheel(0,420);await checkpoint(page,path.join(out,'screenshots'),'11-production-progress')});
  await runChapter(8,'QUẢN LÝ SESSION',async()=>{await nav('session-management','Quản lý Session');await selectByText(page.locator('#smPo'),data.poCode);await page.waitForTimeout(timing.page);const row=page.locator('.session-accordion-trigger').first();if(await row.count())await humanClick(page,row,'Mở chi tiết một session',timing);await checkpoint(page,path.join(out,'screenshots'),'12-session')});
  await runChapter(9,'BÁO CÁO VÀ KPI',async()=>{await nav('dashboard','Dashboard theo ngày');await page.waitForTimeout(timing.important);await checkpoint(page,path.join(out,'screenshots'),'13-report')});
  chapters.push({number:10,title:'OFFLINE MODE',result:'SKIPPED',reason:'Web Kiosk production hiện không có persistent offline queue; không dựng giả chức năng.'});
  chapters.push({number:11,title:'LỊCH LÀM VIỆC',result:'SKIPPED',reason:'Tour không mở form chỉnh lịch production để tránh thay đổi dữ liệu thật.'});
  await context.close(); videoPath=await page.video().path().catch(()=> '');
  const raw=path.join(out,'mesflow-demo-raw.webm');if(videoPath)await fs.copyFile(videoPath,raw);
  const ended=new Date(), report=`# MESFlow Automated Demo Tour Report\n\n- MESFlow version: ${version.trim()}\n- Browser: Chromium\n- Resolution: 1920x1080\n- Mode: ${mode}\n- Start: ${started.toISOString()}\n- End: ${ended.toISOString()}\n- Duration: ${Math.round((ended-started)/1000)} giây\n- Demo data: \`${data.prefix}*\`\n\n## Chapters\n\n| # | Chapter | Result | Note |\n|---:|---|---|---|\n${chapters.map(x=>`| ${x.number} | ${x.title} | ${x.result} | ${(x.reason||'').replaceAll('|','\\|')} |`).join('\n')}\n\n## Artifacts\n\n- Raw video: \`mesflow-demo-raw.webm\`\n- MP4: SKIPPED — ffmpeg không có trong môi trường\n- Screenshots: \`screenshots/\`\n\n## UI issues observed\n\n${uiIssues.length?uiIssues.map(x=>`- ${x}`).join('\n'):'- Không phát hiện lỗi UI rõ ràng trong checkpoint.'}\n\n## Diagnostics\n\n- Browser console errors: ${consoleErrors.length}\n- Failed network requests: ${networkErrors.length}\n${consoleErrors.slice(0,20).map(x=>`- Console: ${x}`).join('\n')}\n${networkErrors.slice(0,20).map(x=>`- Network: ${x}`).join('\n')}\n`;
  await fs.writeFile(path.join(out,'report.md'),report,'utf8');await fs.writeFile(path.join(out,'demo-data.json'),JSON.stringify({...data,entities},null,2),'utf8');console.log(JSON.stringify({ok:true,mode,version:version.trim(),chapters,output:out},null,2));
}catch(error){
  if(page)await page.screenshot({path:path.join(out,`FAILED-${current.replace(/[^a-z0-9]+/gi,'-')}.png`),fullPage:false}).catch(()=>{});chapters.push({title:current,result:'FAIL',reason:error.message});
  await fs.writeFile(path.join(out,'report.md'),`# MESFlow Automated Demo Tour Report\n\nResult: FAIL\n\nChapter: ${current}\n\nError: ${error.stack}\n\n## Console errors\n${consoleErrors.map(x=>`- ${x}`).join('\n')}\n\n## Network errors\n${networkErrors.map(x=>`- ${x}`).join('\n')}\n`,'utf8');
  if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});console.error(error);process.exitCode=1;
}finally{if(browser)await browser.close().catch(()=>{})}
